Project 2 (MadLibs)/CS3620_Project2/madlibs/urls.py
from . import views
from django.urls import path

app_name = 'madlibs'
urlpatterns = [
    path('', views.index, name="index"),
    path('madlib/', views.madlib, name="madlib")
]


Project 2 (MadLibs)/CS3620_Project2/project2/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('madlibs/', include('madlibs.urls')),
]

Project 2 (MadLibs)/CS3620_Project2/madlibs/models.py
from django.db import models


# Create your models here.
class Madlibs(models.Model):

    def __str__(self):
        return self.noun + self.adjective + self.city + self.noun2 + self.pronoun + self.verb + self.noun3

    noun = models.CharField(max_length=20, default="")
    adjective = models.CharField(max_length=20, default="")
    city = models.CharField(max_length=20, default="")
    noun2 = models.CharField(max_length=20, default="")
    pronoun = models.CharField(max_length=20, default="")
    verb = models.CharField(max_length=20, default="")
    noun3 = models.CharField(max_length=20, default="")

Project 2 (MadLibs)/CS3620_Project2/madlibs/forms.py
from django import forms
from.models import Madlibs


class MadlibForm(forms.ModelForm):
    class Meta:
        model = Madlibs
        fields = ['noun', 'adjective', 'city', 'noun2', 'pronoun', 'verb', 'noun3']

Project 2 (MadLibs)/CS3620_Project2/madlibs/views.py
import random
from django.shortcuts import render, redirect
from.forms import MadlibForm
from.models import Madlibs


# Create your views here.
def index(request):
    form = MadlibForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('madlibs:madlib')

    return render(request, 'madlibs/index.html', {'form': form})


def madlib(request):
    input_list = Madlibs.objects.all().last()
    context = {
        'input_list': input_list,
    }
    randomStory = [
        'madlibs/madlib.html',
        'madlibs/madlib2.html',
        'madlibs/madlib3.html',
        'madlibs/madlib4.html',
        'madlibs/madlib5.html',
        'madlibs/madlib6.html',
        'madlibs/madlib7.html',
        'madlibs/madlib8.html',
        'madlibs/madlib9.html',
        'madlibs/madlib10.html',
        'madlibs/madlib11.html',
        'madlibs/madlib12.html',
        'madlibs/madlib13.html',
        'madlibs/madlib14.html',
        'madlibs/madlib15.html',
    ]
    pickRandom = random.choice(randomStory)
    return render(request, pickRandom, context)

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/index.html
{% extends 'madlibs/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to Mad Libs!</title>
</head>
<body class="background-home">
{% block body %}
    <div class="container bg-dark">
        <div class="row banner text-center">
            <div class="col-lg-12 intro">
                <h1 class="welcome">
                    Welcome to Mad Libs!
                </h1>
                <h3 class="fill-form">
                    Fill in the form below and click submit to generate your Mad Lib.
                </h3>
            </div>
        </div>
        <div class="row form d-flex justify-content-center">
            <div class="col-lg-4">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <p class="form-titles">{{ field.name }}:</p>
                            <br>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class="btn btn-success">GO MAD!!!</button>
                </form>
            </div>
            <div class="col-lg-6">
                <div class="card explain">
                    <p><b>Noun</b> - a word that names something, such as a person, place, thing, or idea (For example: Car, House, Child)</p>
                    <p><b>Adjective</b> - describes something (For example: Green, Squishy, Cute)</p>
                    <p><b>Pronoun</b> - are the words you substitute for other nouns when your reader or listener already knows which nouns you’re referring to. For example, you might say, “I have a dog. <i>He’s</i> brown and white.” Other examples include He, Him, She, and Her.</p>
                    <p><b>Verb</b> - are words that show an action (For example: Run, Jump, Swim)</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Statue Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>One day my <span class="madlib">{{ input_list.noun }}</span> saw a <span class="madlib">{{ input_list.adjective }}</span> statue in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>They called their <span class="madlib">{{ input_list.noun2 }}</span> and told <span class="madlib">{{ input_list.pronoun }}</span> to come <span class="madlib">{{ input_list.verb }}</span> with them and their <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib10.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">At the Park Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>Today my super sweet <span class="madlib">{{ input_list.noun }}</span> came with me to the <span class="madlib">{{ input_list.adjective }}</span> park in <span class="madlib">{{ input_list.city }}</span> city.</p><br>
                <p>They brought their pet <span class="madlib">{{ input_list.noun2 }}</span> with them. We decided to go to the park with the large field. At the park we saw <span class="madlib">{{ input_list.pronoun }}</span> just standing there.</p><br>
                <p>They are really hilarious when they <span class="madlib">{{ input_list.verb }}</span>. They even brought their <span class="madlib">{{ input_list.noun3 }}</span> with them.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib12.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Swimming Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>Today I went swimming with my <span class="madlib">{{ input_list.noun }}</span> at the <span class="madlib">{{ input_list.adjective }}</span> swimming pool in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>My friend came with me and brought their <span class="madlib">{{ input_list.noun2 }}</span>. When we were there <span class="madlib">{{ input_list.pronoun }}</span> started jumping off the diving board.</p><br>
                <p>They also wanted to <span class="madlib">{{ input_list.verb }}</span> and play with their <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib13.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Food Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>I love when my <span class="madlib">{{ input_list.noun }}</span> brings me home some <span class="madlib">{{ input_list.adjective }}</span> food from <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>It's even better when my <span class="madlib">{{ input_list.noun2 }}</span> brings me something delicious. Sometimes I share with <span class="madlib">{{ input_list.pronoun }}</span>.</p><br>
                <p>Most of the time I just <span class="madlib">{{ input_list.verb }}</span> and try to hide so I only have to share with my <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib14.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">TV Show Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>I was sitting on my couch looking at my <span class="madlib">{{ input_list.noun }}</span> when a new show called "<span class="madlib">{{ input_list.adjective }}</span> heroes" came on the tv. It's filmed in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>It's about a <span class="madlib">{{ input_list.noun2 }}</span> that save the city from evil villains. The city always cheers for <span class="madlib">{{ input_list.pronoun }}</span> when the city is saved.</p><br>
                <p>The sequel is about a <span class="madlib">{{ input_list.verb }}</span>ing <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib15.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Road Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>Today I was driving around with my <span class="madlib">{{ input_list.noun }}</span> in the passenger seat. I loved looking at the <span class="madlib">{{ input_list.adjective }}</span> sites in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>I saw something on the side of the road and picked it up. It was a <span class="madlib">{{ input_list.noun2 }}</span>. Turns out it belonged to <span class="madlib">{{ input_list.pronoun }}</span>, the most mysterious person around.</p><br>
                <p>I wanted to keep it so I decided to <span class="madlib">{{ input_list.verb }}</span> and try to hide so I could keep it with my <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib2.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Driving Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>I was driving down the road when my <span class="madlib">{{ input_list.noun }}</span> flew out the window and landed on the road.</p><br>
                <p>I came back to see the damage and it was <span class="madlib">{{ input_list.adjective }}</span>. This could only happen in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>I took my <span class="madlib">{{ input_list.noun2 }}</span> with me and that was when <span class="madlib">{{ input_list.pronoun }}</span> called.</p><br>
                <p>They told me to go <span class="madlib">{{ input_list.verb }}</span> with them and their <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib3.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Forest Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>One time while I was in the forest my <span class="madlib">{{ input_list.noun }}</span> turned into something <span class="madlib">{{ input_list.adjective }}</span> right before my eyes. You could see it all the way from <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>Suddenly my <span class="madlib">{{ input_list.noun2 }}</span> started to rip through the forest and then <span class="madlib">{{ input_list.pronoun }}</span> yelled out the most frightening cry.</p><br>
                <p>Next time I am going to <span class="madlib">{{ input_list.verb }}</span> with my <span class="madlib">{{ input_list.noun3 }}</span> instead.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib5.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">In the Sky Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>Walking around my neighborhood with my <span class="madlib">{{ input_list.noun }}</span> I looked up in the sky and saw a <span class="madlib">{{ input_list.adjective }}</span> spaceship flying over <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>My <span class="madlib">{{ input_list.noun2 }}</span> was walking with me at the time. As the spaceship landed and I could see a person come out.</p><br>
                <p><span class="madlib">{{ input_list.pronoun }}</span> told me to <span class="madlib">{{ input_list.verb }}</span> off a ledge and fly with their <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib6.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">At the Movies Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>I love going to see movies with my <span class="madlib">{{ input_list.noun }}</span>. Last time we went we saw the movie "The <span class="madlib">{{ input_list.adjective }}</span> dog" in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>I enjoy going to the movies and my <span class="madlib">{{ input_list.noun2 }}</span> does too because <span class="madlib">{{ input_list.pronoun }}</span> loves to get buttery popcorn.</p><br>
                <p>The movie is about a dog that <span class="madlib">{{ input_list.verb }}</span> around with their <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib7.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Traveling Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>I was traveling with my <span class="madlib">{{ input_list.noun }}</span> the other day. I noticed that there are very <span class="madlib">{{ input_list.adjective }}</span> people that live in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>My favorite thing to bring with me is my <span class="madlib">{{ input_list.noun2 }}</span>. Last time I traveled, I ran into <span class="madlib">{{ input_list.pronoun }}</span> at the store.</p><br>
                <p>They asked me to <span class="madlib">{{ input_list.verb }}</span> for them and to take their <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib8.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Neighborhood Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>Walking around my neighborhood with my <span class="madlib">{{ input_list.noun }}</span> I looked around and noticed a <span class="madlib">{{ input_list.adjective }}</span> plant. I thought to myself this is an unusual plant to see in <span class="madlib">{{ input_list.city }}</span>.</p><br>
                <p>Me and my <span class="madlib">{{ input_list.noun2 }}</span> walked over to the plant and <span class="madlib">{{ input_list.pronoun }}</span> started to talk.</p><br>
                <p>They asked me to <span class="madlib">{{ input_list.verb }}</span> and give them a <span class="madlib">{{ input_list.noun3 }}</span>.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

Project 2 (MadLibs)/CS3620_Project2/madlibs/templates/madlibs/madlib9.html
{% extends 'madlibs/base.html' %}
{% include 'madlibs/index.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mad Libs</title>
</head>
<body>

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <h2 class="madlib-title">Dark Mad Lib</h2>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-lg-7 madlib-story">
                <p>Me and my <span class="madlib">{{ input_list.noun }}</span> were outside when it became dark. The <span class="madlib">{{ input_list.adjective }}</span> lights in the city of <span class="madlib">{{ input_list.city }}</span> were a sight to behold.</p><br>
                <p>They looked almost similar to a <span class="madlib">{{ input_list.noun2 }}</span>. I could see that <span class="madlib">{{ input_list.pronoun }}</span> would be afraid of such things.</p><br>
                <p>You better <span class="madlib">{{ input_list.verb }}</span> and see it with your <span class="madlib">{{ input_list.noun3 }}</span> the next time you are in the dark.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center">
                <a href="{% url 'madlibs:index' %}"><button class="btn btn-success">Start Over</button></a>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>