CS3620_Portfolio (Coding Challenge 6)/CS3620_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PortfolioDatabase/', include('PortfolioDatabase.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/urls.py
from . import views
from django.urls import path


app_name = 'PortfolioDatabase'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('hobbies/', views.hobbies, name='hobbies'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('hobbies/<int:hobby_id>', views.hobby_detail, name="hobby_detail"),
    path('portfolio/<int:portfolio_id>', views.portfolio_detail, name="portfolio_detail"),
    path('add', views.create_item, name="create_item"),
    path('update/<int:id>', views.update_item, name="update_item"),
    path('delete/<int:id>', views.delete_item, name="delete_item"),
    path('create_contact', views.create_contact, name="create_contact"),
]

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/models.py
from django.db import models


# Create your models here.
class Hobbies(models.Model):

    def __str__(self):
        return self.hobby_name + "- " + self.hobby_desc

    hobby_name = models.CharField(max_length=200)
    hobby_desc = models.CharField(max_length=500)
    hobby_image = models.CharField(max_length=500, default="https://www.iesabroad.org/files/blog/images/amueller/2017-10-23/default_featured_image_29.jpg")


class Portfolio(models.Model):

    def __str__(self):
        return self.portfolio_name + "- " + self.portfolio_desc

    portfolio_name = models.CharField(max_length=200)
    portfolio_desc = models.CharField(max_length=500)
    portfolio_image = models.CharField(max_length=500, default="https://c4.wallpaperflare.com/wallpaper/715/222/467/laptop-macintosh-neon-keyboards-wallpaper-preview.jpg")


class Contact(models.Model):
    c_name = models.CharField(max_length=200, default='')
    c_email = models.CharField(max_length=200, default='')
    c_message = models.CharField(max_length=500, default="Personal Message goes here.")

    def __str__(self):
        return self.c_name + ' --- ' + self.c_email + ' ---  ' + self.c_message

CS3620_Portfolio (Coding Challenge 6)/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username + ' --- ' + self.user.email

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/forms.py
from django import forms
from .models import Portfolio, Contact


class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['portfolio_name', 'portfolio_desc', 'portfolio_image']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['c_name', 'c_email', 'c_message']

CS3620_Portfolio (Coding Challenge 6)/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ProfileForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Portfolio
from .models import Hobbies
from .models import Contact
from .forms import PortfolioForm, ContactForm
from django.template import loader


# Create your views here.
def home(request):
    return render(request, 'PortfolioDatabase/home.html')


def hobbies(request):
    hobby_list = Hobbies.objects.all()
    context = {
        'hobby_list': hobby_list,
    }
    return render(request, 'PortfolioDatabase/hobbies.html', context)


def portfolio(request):
    p_list = Portfolio.objects.all()
    context = {
        'p_list': p_list
    }
    return render(request, 'PortfolioDatabase/portfolio.html', context)


def contact(request):
    contact = Contact.objects.all()
    context = {
        'contact': contact,
    }
    return render(request, 'PortfolioDatabase/contact.html', context)


def hobby_detail(request, hobby_id):
    hobby = Hobbies.objects.get(pk=hobby_id)
    context = {
        'hobby': hobby
    }
    return render(request, 'PortfolioDatabase/hobby_details.html', context)


def portfolio_detail(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    context = {
        'portfolio': portfolio
    }
    return render(request, 'PortfolioDatabase/portfolio_details.html', context)


def create_item(request):
    form = PortfolioForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('PortfolioDatabase:portfolio')

    return render(request, 'PortfolioDatabase/form.html', {'form': form})


def update_item(request, id):
    item = Portfolio.objects.get(id=id)
    form = PortfolioForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('PortfolioDatabase:portfolio')

    return render(request, 'PortfolioDatabase/form.html', {'form': form, 'item': item})


def delete_item(request, id):
    item = Portfolio.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('PortfolioDatabase:portfolio')

    return render(request, 'PortfolioDatabase/portfolio-delete.html', {'item': item})


def create_contact(request):
    form = ContactForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('PortfolioDatabase:contact')

    return render(request, 'PortfolioDatabase/form.html', {'form': form})

CS3620_Portfolio (Coding Challenge 6)/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ProfileForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def register(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}! You have successfully created an account. Please login with your new credentials.')
            return redirect('login')
    else:
        form = ProfileForm()
    return render(request, 'users/register.html', {'form': form})


CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body class="bg-body">
<nav class="navbar bg-secondary">
    <a href="{% url 'PortfolioDatabase:home' %}" class="navbar-brand"><img src="https://icarus.cs.weber.edu/~cc89905/coleman_portfolio/img/portfolio_logo.png" class="card" height="100px" alt=""></a>
    <div class="navbar">
        <a href="{% url 'PortfolioDatabase:home' %}" class="nav-item nav-link ">Home</a>
        <a href="{% url 'PortfolioDatabase:hobbies' %}" class="nav-item nav-link ">Hobbies</a>
        <a href="{% url 'PortfolioDatabase:portfolio' %}" class="nav-item nav-link">Portfolio</a>
        {% if user.is_authenticated %}
            <a href="{% url 'PortfolioDatabase:contact' %}" class="nav-item nav-link">Contact</a>
            <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
        {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
        {% endif %}
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block body %}
{% endblock %}
</body>
</html>

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/contact.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact</title>
</head>
<body>
{% block body %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row align-items-center justify-content-md-center">
                <div class="col-md-0">
                    <a href="{% url 'PortfolioDatabase:create_contact' %}" class="btn btn-info">Add Contact Information</a>
                </div>
            </div>
        </div>
    {% endif %}
    {% for Contact in contact %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-6 contact-info text-white">
                <h1>{{ Contact.c_name }}</h1>
                <h4>{{ Contact.c_email }}</h4>
                <h4>{{ Contact.c_message }}</h4>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}
</body>
</html>

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/form.html
{% extends 'PortfolioDatabase/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-12 text-white">
                {{ form }}
                <button class="btn btn-info" type="submit">Save</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/hobbies.html
{% extends 'PortfolioDatabase/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hobbies</title>
</head>
<body>
{% block body %}
{% for Hobbies in hobby_list %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-3">
                <img class="card" height="300px" width="320px" src="{{ Hobbies.hobby_image }}" alt="">
            </div>
            <div class="col-md-3 text-center text-white">
                <h3>{{ Hobbies.hobby_name }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'PortfolioDatabase:hobby_detail' Hobbies.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/hobby_details.html
{% extends 'PortfolioDatabase/base.html' %}

{% block body %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-4">
                <img src="{{ hobby.hobby_image }}" height="350px" width="340px" alt="">
            </div>
            <div class="col-md-4 text-white">
                <h1>{{ hobby.hobby_name }}</h1>
                <h4>{{ hobby.hobby_desc }}</h4>
            </div>
        </div>
    </div>
{% endblock %}

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/home.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% block body %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-7 text-center text-white">
                <h1 class="intro">Welcome</h1>
            </div>
            <div class="col-md-7 text-center card intro-text">
                <p>My name is Cory Coleman. I am a senior in the Computer Science<br>
                    program at Weber State University. I am working on finishing<br>
                    up my Bachelor's Degree in Web and User experience. I am<br>
                    creating this site through my CS 3620 - Server-side Web<br>
                    Architecture course at Weber State University. I really<br>
                    love working with web development on the front-end side,<br>
                    and I am very excited to be learning more about the<br>
                    back-end side.</p>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/portfolio-delete.html
{% extends 'PortfolioDatabase/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-8 text-white">
                <h2>Are you sure you want to delete {{ item.portfolio_name }}?</h2>
                <button class="btn btn-info" type="submit">Confirm</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/portfolio.html
{% extends 'PortfolioDatabase/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portfolio</title>
</head>
<body>
{% block body %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row align-items-center justify-content-md-center">
                <div class="col-md-1">
                    <a href="{% url 'PortfolioDatabase:create_item' %}" class="btn btn-info">Add Portfolio Item</a>
                </div>
            </div>
        </div>
    {% endif %}
{% for Portfolio in p_list %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-3">
                <img class="card" height="300px" width="320px" src="{{ Portfolio.portfolio_image }}" alt="">
            </div>
            <div class="col-md-3 text-center text-white">
                <h3>{{ Portfolio.portfolio_name }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'PortfolioDatabase:portfolio_detail' Portfolio.id %}" class="btn btn-success">Details</a>
                {% if user.is_authenticated %}
                <a href="{% url 'PortfolioDatabase:update_item' Portfolio.id %}" class="btn btn-warning">Edit </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

CS3620_Portfolio (Coding Challenge 6)/PortfolioDatabase/templates/PortfolioDatabase/portfolio_details.html
{% extends 'PortfolioDatabase/base.html' %}

{% block body %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-4">
                <img src="{{ portfolio.portfolio_image }}" height="350px" width="340px"/>
            </div>
            <div class="col-md-4 text-white">
                <h1 class="align-items-center">{{ portfolio.portfolio_name }}</h1>
                <h4>{{ portfolio.portfolio_desc }}</h4>
                {%  if user.is_authenticated %}
                <a href="{% url 'PortfolioDatabase:delete_item' portfolio.id %}" class="btn btn-info">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

CS3620_Portfolio (Coding Challenge 6)/users/templates/users/login.html
{% extends 'PortfolioDatabase/base.html' %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row align-items-center justify-content-md-center">
                <div class="col-md-8 text-white">
                    {{ form }}
                    <button class="btn btn-info" type="submit">Login</button>
                </div>
            </div>
        </div>
    </form>
    <div>
        <div class="container">
            <div class="row align-items-center justify-content-md-center">
                <div class="col-md-5 text-white">
                    <h3>Please login or you can signup</h3>
                </div>
            </div>
            <div class="row align-items-center justify-content-md-center">
                <div class="col-md-2">
                    <a href="{% url 'register' %}" class="btn btn-info">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CS3620_Portfolio (Coding Challenge 6)/users/templates/users/logout.html
{%  extends 'PortfolioDatabase/base.html' %}

{% block body %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-6 text-white">
                <h2>You have been logged out!</h2>
            </div>
        </div>
    </div>
{% endblock %}

CS3620_Portfolio (Coding Challenge 6)/users/templates/users/register.html
{%  extends 'PortfolioDatabase/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-12 text-white">
                {{ form }}
                <button class="btn btn-info" type="submit">SignUp</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}