CS3620_Portfolio/PortfolioDatabase/urls.py
from . import views
from django.urls import path


app_name = 'PortfolioDatabase'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('hobbies/', views.hobbies, name='hobbies'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('hobbies/<int:hobby_id>', views.hobby_detail, name="hobby_detail"),
    path('portfolio/<int:portfolio_id>', views.portfolio_detail, name="portfolio_detail"),
]

CS3620_Portfolio/PortfolioDatabase/models.py
from django.db import models


# Create your models here.
class Hobbies(models.Model):

    def __str__(self):
        return self.hobby_name + "- " + self.hobby_desc

    hobby_name = models.CharField(max_length=200)
    hobby_desc = models.CharField(max_length=500)
    hobby_image = models.CharField(max_length=500, default="https://www.iesabroad.org/files/blog/images/amueller/2017-10-23/default_featured_image_29.jpg")


class Portfolio(models.Model):

    def __str__(self):
        return self.portfolio_name + "- " + self.portfolio_desc

    portfolio_name = models.CharField(max_length=200)
    portfolio_desc = models.CharField(max_length=500)
    portfolio_image = models.CharField(max_length=500, default="https://c4.wallpaperflare.com/wallpaper/715/222/467/laptop-macintosh-neon-keyboards-wallpaper-preview.jpg")


class Contact(models.Model):

    contact_message = models.CharField(max_length=500, default="https://operations.chicagopolice.org/FIMSPublic/Content/images/default-contact-image.png")

CS3620_Portfolio/PortfolioDatabase/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Portfolio
from .models import Hobbies
from django.template import loader


# Create your views here.
def home(request):
    return render(request, 'PortfolioDatabase/home.html')


def hobbies(request):
    hobby_list = Hobbies.objects.all()
    context = {
        'hobby_list': hobby_list,
    }
    return render(request, 'PortfolioDatabase/hobbies.html', context)


def portfolio(request):
    p_list = Portfolio.objects.all()
    context = {
        'p_list': p_list
    }
    return render(request, 'PortfolioDatabase/portfolio.html', context)


def contact(request):
    return render(request, 'PortfolioDatabase/contact.html')


def hobby_detail(request, hobby_id):
    hobby = Hobbies.objects.get(pk=hobby_id)
    context = {
        'hobby': hobby
    }
    return render(request, 'PortfolioDatabase/hobby_details.html', context)


def portfolio_detail(request, portfolio_id):
    portfolio = Portfolio.objects.get(pk=portfolio_id)
    context = {
        'portfolio': portfolio
    }
    return render(request, 'PortfolioDatabase/portfolio_details.html', context)

CS3620_Portfolio/PortfolioDatabase/templates/PortfolioDatabase/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Portfolio</title>
    <link rel="stylesheet" href="{% static 'PortfolioDatabase/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body class="bg-body">
<nav class="navbar bg-secondary">
    <a href="{% url 'PortfolioDatabase:home' %}" class="navbar-brand"><img src="https://icarus.cs.weber.edu/~cc89905/coleman_portfolio/img/portfolio_logo.png" class="card" height="100px" alt=""></a>
    <div class="navbar">
        <a href="{% url 'PortfolioDatabase:home' %}" class="nav-item nav-link ">Home</a>
        <a href="{% url 'PortfolioDatabase:hobbies' %}" class="nav-item nav-link ">Hobbies</a>
        <a href="{% url 'PortfolioDatabase:portfolio' %}" class="nav-item nav-link">Portfolio</a>
        <a href="{% url 'PortfolioDatabase:contact' %}" class="nav-item nav-link">Contact</a>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

CS3620_Portfolio/PortfolioDatabase/templates/PortfolioDatabase/contact.html
{% extends 'PortfolioDatabase/base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact</title>
</head>
<body>
{% block body %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-6">
                <img src="https://media-exp1.licdn.com/dms/image/C4D03AQEHj5TMHGDEyQ/profile-displayphoto-shrink_800_800/0/1588694814046?e=1670457600&v=beta&t=IP8PO16NqAtFqnEWNnj0iPZhR7GsR7_sG76vqEMUicQ" class="card contact" height="250px" alt="">
            </div>
            <div class="col-md-6 contact-info text-white">
                <h1>Contact me:</h1>
                <h4>Phone: 801-599-0862</h4>
                <h4>Email: corycoleman@mail.weber.edu</h4>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

CS3620_Portfolio/PortfolioDatabase/templates/PortfolioDatabase/portfolio.html
{% extends 'PortfolioDatabase/base.html' %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Portfolio</title>
</head>
<body>
{% block body %}
{% for Portfolio in p_list %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-3">
                <img class="card" height="300px" width="320px" src="{{ Portfolio.portfolio_image }}" alt="">
            </div>
            <div class="col-md-3 text-center text-white">
                <h3>{{ Portfolio.portfolio_name }}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'PortfolioDatabase:portfolio_detail' Portfolio.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

CS3620_Portfolio/PortfolioDatabase/templates/PortfolioDatabase/portfolio_details.html
{% extends 'PortfolioDatabase/base.html' %}

{% block body %}
    <div class="container">
        <div class="row align-items-center justify-content-md-center">
            <div class="col-md-4">
                <img src="{{ portfolio.portfolio_image }}" height="350px" width="340px"/>
            </div>
            <div class="col-md-4 text-white">
                <h1 class="align-items-center">{{ portfolio.portfolio_name }}</h1>
                <h4>{{ portfolio.portfolio_desc }}</h4>
            </div>
        </div>
    </div>
{% endblock %}